<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class kurikulum_subjekTableSeeders extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //check if table kurikulumsubjek is empty
        if(DB::table("kurikulum_subjek")->count() == 0){

            DB::table("kurikulum_subjek")->insert([ 
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Bahasa Melayu",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Bahasa Inggeris",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Matematik Awal",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Sains Awal",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Kemanusiaan",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Keterampilan diri",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Kreativiti dan Estetika",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Pendidikan Moral",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Perkembangan Fizikal dan Penjagaan Kesihatan",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSPK - Kurikulum Standard Pra Sekolah Kebangsaan",
                    "subjek" => "Pendidikan Islam",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Bahasa Melayu",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Bahasa Inggeris",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Matematik",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Sains",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Pendidikan Islam",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Pendidikan Moral",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Pendidikan Jasmani",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Pendidikan Kesihatan",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Muzik",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Bahasa Cina",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Bahasa Tamil",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Sejarah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Reka Bentuk dan Teknologi",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSR Semakan - Kurikulum Standard Sekolah Rendah Semakan",
                    "subjek" => "Teknologi Maklumat dan Komunikasi",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Tilawah Al-Quran",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Tauhid",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Feqah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Sirah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Akhlak",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Bahasa Arab",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Jawi",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Khat",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Tajwid",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Imlak",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSRA - Kurikulum Sekolah Rendah Agama",
                    "subjek" => "Hafazan",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KAFA - Kurikulum Fardhu Ain dan Alquran",
                    "subjek" => "Al-Quran",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KAFA - Kurikulum Fardhu Ain dan Alquran",
                    "subjek" => "Akidah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KAFA - Kurikulum Fardhu Ain dan Alquran",
                    "subjek" => "Ibadah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KAFA - Kurikulum Fardhu Ain dan Alquran",
                    "subjek" => "Sirah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KAFA - Kurikulum Fardhu Ain dan Alquran",
                    "subjek" => "Adab",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KAFA - Kurikulum Fardhu Ain dan Alquran",
                    "subjek" => "Bahasa Arab",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KAFA - Kurikulum Fardhu Ain dan Alquran",
                    "subjek" => "Jawi dan Khat",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KAFA - Kurikulum Fardhu Ain dan Alquran",
                    "subjek" => "Tahfiz Al-Quran",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Bahasa Melayu",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Bahasa Inggeris",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Matematik",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Sains",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Sejarah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Pendidikan Islam",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Pendidikan Moral",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Biologi",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Kimia",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Fizik",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Matematik Tambahan",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Sains Sukan",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Ekonomi Rumah Tangga",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Sains Komputer",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Pertanian",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Grafik Komunikasi Teknikal",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Reka Cipta",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Ekonomi",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah",
                    "subjek" => "Prinsip Perakaunan",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Pendidikan Seni Visual",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Pendidikan Muzik",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Geografi",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Kesusasteraan Melayu",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Pendidikan Al-Quran & Al-Sunnah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Syariah Islamiah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Tasawwur Islam",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Usul Al-Din",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Al-Syariah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Muzik",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Seni Halus",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Teater",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Tari",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Komunikasi Visual",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Reka Bentuk",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Cina",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Tamil",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Arab",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Iban",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Kadazandusun",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Semai",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Punjabi",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Jepun",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Jerman",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Korea",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSSM - Kurikulum Standard Sekolah Menengah", 
                    "subjek"=> "Cina Komunikasi",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSKP- Kurikulum Standard Kelas Peralihan",
                    "subjek"=> "Bahasa Melayu",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSKP- Kurikulum Standard Kelas Peralihan",
                    "subjek"=> "Amalan Bahasa Melayu",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSKP- Kurikulum Standard Kelas Peralihan",
                    "subjek"=> "Bahasa Inggeris",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSKP- Kurikulum Standard Kelas Peralihan",
                    "subjek"=> "Tamil",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSKP- Kurikulum Standard Kelas Peralihan",
                    "subjek"=> "Cina",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSKP- Kurikulum Standard Kelas Peralihan",
                    "subjek"=> "Pendidikan Jasmani dan Pendidikan Kesihatan",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KSKP- Kurikulum Standard Kelas Peralihan",
                    "subjek"=> "Pendidikan Seni Visual",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KBD- Kurikulum Bersepadu Dini",
                    "subjek"=> "Syariah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KBD- Kurikulum Bersepadu Dini",
                    "subjek"=> "Usuluddin",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KBD- Kurikulum Bersepadu Dini",
                    "subjek"=> "Al-Lughah Al-Arabiah Al-Mu'arisah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KBD- Kurikulum Bersepadu Dini",
                    "subjek"=> "Manahij Al-Ulum Al-Islamiah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KBD- Kurikulum Bersepadu Dini",
                    "subjek"=> "Al-Adab Al-Mu'arisah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KBD- Kurikulum Bersepadu Dini",
                    "subjek"=> "Al-Adab Wa Al-Balaghah",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KBT- Kurikulum Bersepadu Tahfiz",
                    "subjek"=> "Hifz Al-Quran",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
                [
                    "kurikulum" => "KBT- Kurikulum Bersepadu Tahfiz",
                    "subjek"=> "Maharat Al-Quran",
                    'created_at'=>date('Y-m-d H:i:s'),
                    'updated_at'=>date('Y-m-d H:i:s'),
                ],
            ]);
        }
    }
}
